### ISSUE TITLE
can not do multiple evaluations at once

### ISSUE THREAD

**Issue by k8sansom** [pasqualerossi/42-School-Guide#1]
42 has said that it is considered cheating to hold overlapping evaluations.

**Comment by pasqualerossi** [comment]
I can understand where they are coming from, however I think the 42intra still allows 3 evaluations to be booked at the same time, unless that’s changed?

**Comment by k8sansom** [comment]
Maybe it’s just 42 Berlin, but it’s a violation that will result in
community service here.
From the Notion summary table of violations and sanctions:
“Scheduling evaluations at the same time to do a ‘group evaluation’ instead
of individual evaluations:
Evaluations will be destroyed. The evaluator and evaluee loses an
evaluation point and both will receive community service.”

**Comment by ivotints** [comment]
42 Prague do not allow multiple evaluations. Only one by one
